version     = "0.1.0"
author      = "Softmax"
description = "Three cogs hide, three cogs seek: movable crates, lockable ramps and torch-beam vision cones on a continuous-2D line-of-sight runtime."
license     = "MIT"

srcDir = "src"

requires "nim >= 2.2.4"
requires "bitworld >= 0.1.0"
requires "pixie"
requires "mummy >= 0.4.7"
requires "curly >= 1.1.1"
requires "silky >= 0.0.2"
requires "windy >= 0.4.4"
requires "paddy >= 0.1.0"
requires "supersnappy >= 2.1.3"
requires "jsony"
requires "zippy"
requires "flatty >= 0.3.4"
requires "fluffy >= 1.0.0"
requires "crunchy >= 0.1.11"
